name: Compile PDFs

# Compile new PDFs on any push event
on:
  push:
    branches:
        - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    container: thomasweise/texlive

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Fonts & Utils
        run: |
          apt-get update -y
          apt-get install -y texlive-bibtex-extra biber unzip
          apt-get install -y fonts-font-awesome fonts-roboto
          wget https://www.fontsquirrel.com/fonts/download/source-sans-pro.zip
          mkdir -p ~/.fonts
          unzip source-sans-pro.zip -d ~/.fonts
          fc-cache -f -v

      # Use included Makefile
      - name: Compile
        run: |
          cd examples
          mkdir build
          make

      # Upload new PDFs as a new release
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.CV_SECRET }}
          automatic_release_tag: "latest"
          files: |
            examples/build/cv.pdf
            examples/build/resume.pdf
            examples/build/coverletter.pdf
